Repository HapticX/happyx, pull requests merged in 2024-06, with the labels that each got.

#288 fix formDataSeparator regex, skip empty lines
  src/happyx/ssr/form_data.nim
Labels: bug, ssg, ssr

#292 new release v3.12.0
  examples/website/src/components/about_section.nim
  examples/website/src/docs/introduction.nim
  examples/website/src/pages/home.nim
  src/happyx/private/macro_utils.nim
  src/happyx/spa/renderer.nim
  src/happyx/spa/translatable.nim
  src/happyx/ssr/docs/autodocs.nim
  tests/index18.html
  tests/testc2.nim
  tests/testjs18.nim
  tests/testjs9.nim
Labels: enhancement

#294 website upgrade
  examples/website/src/components/guide_page.nim
  examples/website/src/components/sidebar.nim
  examples/website/src/docs/docs.nim
  examples/website/src/docs/spa_basics.nim
  examples/website/src/docs/spa_rendering.nim
  examples/website/src/ui/code/nim_spa.nim
  examples/website/src/ui/translations.nim
  src/happyx/spa/translatable.nim
Labels: documentation

#296 version 4.0.0
  examples/sandbox_api/src/main.nim
  examples/website/src/components/drawer.nim
  examples/website/src/components/guide_page.nim
  examples/website/src/components/sidebar.nim
  examples/website/src/docs/docs.nim
  examples/website/src/docs/mounting.nim
  examples/website/src/docs/path_params.nim
  examples/website/src/pages/sandbox.nim
  examples/website/src/ui/code/javascript.nim
  examples/website/src/ui/code/nim_spa.nim
  examples/website/src/ui/code/nim_ssr.nim
  examples/website/src/ui/code/python.nim
  examples/website/src/ui/code/typescript.nim
  examples/website/src/ui/translations.nim
  happyx.nimble
  screenshots/component_button.gif
  screenshots/component_card.gif
  screenshots/component_input.gif
  screenshots/component_progress.png
  src/happyx.nim
  src/happyx/bindings/java.nim
  src/happyx/bindings/node.nim
  src/happyx/bindings/python.nim
  src/happyx/cli/create_command.nim
  src/happyx/cli/project_info_command.nim
  src/happyx/cli/update_command.nim
  src/happyx/cli/utils.nim
  src/happyx/core/constants.nim
  src/happyx/private/macro_utils.nim
  src/happyx/private/scanutils.nim
  src/happyx/routing/routing.nim
  src/happyx/spa/components.nim
  src/happyx/spa/renderer.nim
  src/happyx/spa/spa_utils.nim
  src/happyx/spa/tag.nim
  src/happyx/spa/translatable.nim
  src/happyx/ssr/docs/api_doc_template.nim
  src/happyx/ssr/docs/autodocs.nim
  src/happyx/ssr/form_data.nim
  src/happyx/ssr/handlers.nim
  src/happyx/ssr/server.nim
  src/happyx/sugar/js.nim
  src/happyx/sugar/style.nim
  tests/testc1.nim
  tests/testc16.nim
  tests/testc17.nim
  tests/testc18.nim
  tests/testc2.nim
  tests/testc5.nim
  tests/testc6.nim
  tests/testjs16.nim
  tests/testjs18.nim
  tests/testjs2.nim
Labels: release

#299 New patch
  .github/workflows/examples.yml
  .github/workflows/gh-pages.yml
  .github/workflows/language_bindings.yml
  .github/workflows/tests.yml
  README.md
  bindings/python/MANIFEST.in
  bindings/python/README.md
  bindings/python/happyx/happyx.pyd
  bindings/python/happyxpy/__init__.py
  bindings/python/happyxpy/constants.py
  bindings/python/happyxpy/happyx.pyd
  bindings/python/happyxpy/server.py
  bindings/python/setup.py
  bindings/python/test1.py
  bindings/python/test2.py
  build_py.cmd
  build_py_debug.cmd
  examples/website/src/components/guide_page.nim
  examples/website/src/components/sidebar.nim
  examples/website/src/docs/docs.nim
  examples/website/src/docs/for_users/karax.nim
  examples/website/src/ui/code.nim
  examples/website/src/ui/code/karax.nim
  examples/website/src/ui/code/python.nim
  examples/website/src/ui/translations.nim
  src/happyx/spa/components.nim
  src/happyx/spa/renderer.nim
  src/happyx/spa/tag.nim
  src/happyx/spa/translatable.nim
  tests/testjs18.nim
Labels: documentation
